version: '4'
services:
  queue:
    image: bitnami/rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 5672 # Main port
      - 15672 # Management console
    restart: always
